### ISSUE TITLE
V2 roadmap

### ISSUE THREAD

**Issue by Enubia** [Enubia/ghost-chat#426]
## general
- [x] upgrade all dependencies
- [x] rewrite core logic
- [x] fix window management
- [x] replace tailwind with pico
- [x] rework config logic
- [x] add logger for crash reporting
- [x] [auto updater](https://www.electron.build/auto-update.html)
- [x] automate build pipelines (mac support is coming back, makes it easier to publish)
- [x] i18n support
- [ ] ~~add opt-in analytics~~
- [ ] ~~linux support~~

## chat
- [x] add [Kapchat](https://nightdev.com/kapchat) instead of a custom chat implementation
- [ ] ~~add an option to load any browser source (like streamlabs chat)~~

## settings
- [x] add a popout settings page
- [x] default chat option
- [x] chat options for kapchat (check what can be customized)
- [x] CSS editor (needed for the user to inject custom CSS if needed into the browser source)
- [x] JS injection?
- [ ] ~custom colors?~

### general
- [x] `open config` tray menu option should open folder and not the config in the default editor
- [x] notify user about chat theme change to start the chat again
- [x] add info about KapChat css classes 

### mac
- [x] check default channel not applying
- [x] add option to minimize instead of closing the app (simply, add default behavior on mac back)
- [x] check event order, icon is created in dock and removed once window is launched
- [ ] ~~check brew.sh support~~

# additional requests are welcome in case I missed something important
